on: push
jobs:
  takepic:
    runs-on:  windows-latest
    steps:
    - name: screenshot-website
      uses: switon/screenshot-website@v1.0.0
      with:
          source: https://kathaa.ml/7777/5.htm
          destination: today.png
    - name: upl
      uses: actions/upload-artifact@v2
